### ISSUE TITLE
data.js

### ISSUE THREAD

**Issue by abr4xas** [RCHowell/Music-Blog#1]
Hi, how build a JSON array for 'backend' and how to use on data.js file?

**Comment by RCHowell** [comment]
1) Make a google spreadsheet
2) Publish the spreadsheet to web (it should be under the file tab)
3) make a $.getJSON call to this URL

https://spreadsheets.google.com/feeds/list/[key]/od6/public/values?alt=json

4) replace [key] with your spreadsheet's unique key (the long string of
characters in your spreadsheets URL)
5) That should be it. Let me know if you have questions. It will return one
huge JSON object with the spreadsheets data

**Comment by abr4xas** [comment]
Thx!! :D

----
ángel cruz
http://blog.abr4xas.org
GNU/Linux counter #50841
